name: CI Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Navigate to project directory
        run: cd Xamarin.Forms-Samples

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build Android app
        run: |
          dotnet build -c Release -t:restore,build /p:Configuration=Release /p:Platform=AnyCPU /p:AndroidBuildApplicationPackage=true /p:AndroidSdkBuildToolsVersion=29.0.2

      - name: Build iOS app
        run: |
          dotnet build -c Release -t:restore,build /p:Configuration=Release /p:Platform=iPhone

      - name: Upload Android artifact
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: DualScreen.Droid/bin/Release/com.example.app.apk

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS
          path: DualScreen.iOS/bin/iPhone/Release/DualScreen.iOS.app
