name: CI Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  CHECKOUT-REPO:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  Android-BUILD:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and Package Android App
        run: |
          cd Blank
          nuget restore
          cd Blank.Android
          msbuild Blank.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug 
      - name: Upload Android App Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Android App
          path: Blank/Blank.Android/bin/Debug/com.tfp.blank-Signed.apk

  iOS_BUILD:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build iOS Simulator App
        run: |
          cd Blank
          nuget restore
          msbuild Blank.iOS/Blank.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
      - name: Upload iOS Simulator App Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS Simulator App
          path: Blank/Blank.iOS/bin/iPhoneSimulator/Debug/Blank.iOS.app
